### ISSUE TITLE
[Front] Componente de Loading

### ISSUE THREAD

**Issue by pipoFFG** [pipoFFG/tzedaka#32]
Esta tarea consiste en:
1) Hacer una pantalla con alguna animación cuando se transiciona de una pantalla a otra. Tomar de referencia la pantalla de Loading de la página de Tzedaká. 
2) Se debe hacer un render condicional en donde si no se completó el fetch del back, que muestre esta pantalla de loading.

**Comment by juanchi-ffg** [comment]
Loading agregado, falta agregarlo a todas las llamadas al back una vez que las hayamos incluido.
