### ISSUE TITLE
[Front] Pantalla de errores

### ISSUE THREAD

**Issue by pipoFFG** [pipoFFG/tzedaka#33]
Definir errores posibles y crear una pantalla para cada error con un mensaje descriptivo.

**Comment by jmestanza-ffg** [comment]
Los posibles casos de errores pueden ser:
- El back no está respondiendo
- El usuario de Clerk no está en la base de salesforce
- Después de submitear el form de Contacto hubo un error

**Comment by juanchi-ffg** [comment]
Pantalla de error creada, falta incluirla en todas las paginas que requieran de una (profile ya la tiene).
